# Usa la imagen base de OpenJDK
FROM openjdk:17-jdk-slim

# Establece el directorio de trabajo
WORKDIR /app

# Copia el archivo JAR de tu aplicación al contenedor
COPY build/libs/*.jar app.jar

# Expone el puerto que usa tu aplicación
EXPOSE 8087

# Comando para ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "app.jar"]
