spring.application.name=api-device-management

server.port=8086
server.servlet.context-path=/device-management

# Configuraci�n de MongoDB
spring.data.mongodb.uri=mongodb+srv://alejolml2:8wFhOGSMmv9Lhlsx@codechallenge.1gbj4.mongodb.net/codeChallenge

# Consola de administraci�n de MongoDB
spring.data.mongodb.database=codeChallenge
