spring.application.name=api-user-management

server.port=8087
server.servlet.context-path=/user-management

# Configuraci�n de MongoDB
spring.data.mongodb.uri=mongodb+srv://alejolml2:8wFhOGSMmv9Lhlsx@codechallenge.1gbj4.mongodb.net/codeChallenge

# Consola de administraci�n de MongoDB
spring.data.mongodb.database=codeChallenge
